Database:
  Type: sqlite # pgsql, sqlite, mysql
  Host: localhost
  Port: 5432
  Name: dominion
  User: dominion
  Pass: dominion

Language: zh-cn

AutoCreateRadius: 10
DefaultJoinMessage: '&3{OWNER}: Welcome to {DOM}!'
DefaultLeaveMessage: '&3{OWNER}: Leaving {DOM}...'

MessageDisplay:
  NoPermission: ACTION_BAR
  JoinLeave: ACTION_BAR

Limit:
  SpawnProtection: 10
  MinY: -64
  MaxY: 320
  Size:
    MaxX: 128
    MaxY: 64
    MaxZ: 128
    MinX: 4
    MinY: 4
    MinZ: 4
  Amount: 10
  Depth: 3
  Vert: false
  OpByPass: true
  WorldSettings:
    some_world_name:
      MinY: -64
      MaxY: 320
      Size:
        MaxX: 128
        MaxY: 64
        MaxZ: 128
        MinX: 4
        MinY: 4
        MinZ: 4
      Amount: 10
      Depth: 3
      Vert: false

Teleport:
  Enable: true
  Delay: 0
  CoolDown: 0

AutoCleanAfterDays: 180

Tool: ARROW

Economy:
  Enable: false
  Price: 10.0
  OnlyXZ: false
  Refund: 0.85

FlyPermissionNodes:
  - essentials.fly
  - cmi.command.fly

ResidenceMigration: false

GroupTitle:
  Enable: false
  Prefix: "["
  Suffix: "]"

BlueMap: false
Dynmap: false

CheckUpdate: true

Debug: false

Timer: false